version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-major"]
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "chore"
          prefix-development: "chore"
          include: "scope"
      groups:
          dependencies:
              patterns: ["*"]

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "chore"
          prefix-development: "chore"
          include: "scope"
      groups:
          github-actions:
              patterns: ["*"]
